env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/essential'
  # google风格 https://github.com/google/eslint-config-google 
  - google
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
rules: {}
